name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Restore packages
        run: nuget restore
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test --verbosity normal
      - name: Package
        run: dotnet pack -c Release
      - name: Add Package Repo
        run: dotnet nuget add source --username MarkusPalcer --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/MarkusPalcer/index.json"
      - name: Publish if version has changed
        run: dotnet nuget push **/Release/*.nupkg -s "github" --skip-duplicate