name: Pull-Request

on: pull_request

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [8.0.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build --verbosity normal