name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Restore packages
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test --verbosity normal
      - name: Package
        run: dotnet pack -c Release
      - name: Publish if version has changed
        run: dotnet nuget push **/Release/*.nupkg -s https://www.nuget.org -k ${{ secrets.NUGET_KEY }} --skip-duplicate